repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.5.3"
    hooks:
      - id: prettier
        args: [--prose-wrap=always]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix, "--show-fixes"]
      - id: ruff-format
